#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export MODEL="${MODEL:-md4}"
export EXPERIMENT_CFG="${EXPERIMENT_CFG:-md4_cifar10}"
export EVAL_CFG="${EVAL_CFG:-sjd_cifar10}"

export JOB_NAME="${JOB_NAME:-sticky_md4}"
export PARTITION="${PARTITION:-ai}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-2}"
export CPUS_PER_TASK="${CPUS_PER_TASK:-48}"
export MEMORY="${MEMORY:-480G}"
export TIME_LIMIT="${TIME_LIMIT:-24:00:00}"

export PLATFORM="${PLATFORM:-pmap}"
export REQUIRED_LOCAL_DEVICES="${REQUIRED_LOCAL_DEVICES:-${GPUS_PER_NODE}}"

export BATCH_SIZE="${BATCH_SIZE:-256}"
export EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-${BATCH_SIZE}}"
export TRAIN_STEPS="${TRAIN_STEPS:-2000000}"
export LOG_EVERY="${LOG_EVERY:-500}"
export METRICS_EVERY="${METRICS_EVERY:-1000}"
export CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-10000}"
export LOG_IMAGES_EVERY="${LOG_IMAGES_EVERY:-}"
export SAVE_FINAL_CHECKPOINT="${SAVE_FINAL_CHECKPOINT:-true}"

export WANDB_ENABLED="${WANDB_ENABLED:-true}"
export EVAL_ENABLED="${EVAL_ENABLED:-false}"
export BASELINE_ARCH_114M="${BASELINE_ARCH_114M:-false}"
export DISABLE_AUGMENT="${DISABLE_AUGMENT:-true}"
export DISABLE_CORRECTOR="${DISABLE_CORRECTOR:-false}"

exec "${SCRIPT_DIR}/submit_train.sh"
