defaults:
  - /model/backbone@_here_: gpt2_like_sudoku_inpaint_6m
  - _self_

name: mdlm

cont_time: true
timesteps: 50
noise_schedule_type: loglinear
time_features: none

antithetic_time_sampling: true
classes: -1
cache_predictions: false
