defaults:
  - base
  - _self_

name: sudoku_mdlm

num_train_steps: 3500000

log_every_steps: 500
timing_warn_seconds: 15
eval_every_steps: 10000
checkpoint_every_steps: 10000
checkpoint_keep: 5
log_images_every_steps: 0

best_checkpoint_metric: eval/acc_board_exact
best_checkpoint_mode: max

sample_timesteps: ${..sampler.n_steps}
