# config/dataset/cifar10_discrete.yaml
name: cifar10_discrete
data_dir: "data/cifar10"

# global batch size for pmap path
batch_size: 128
eval_batch_size: 128

per_device_batch_size: -1

data_shape: [32, 32, 3]
vocab_size: 256
num_classes: -1  # unconditional by default (set to 10 for class-conditional)
